name = input("Type your name")
print(name)
age = input("How old are you?")
print(age)
color = input(" What is you're favorite color")
print(color) 
print ("Hello",name, "you are", age,"years old and your favorite color is",color)